version: '3.8'

services:
  datadictionary:
    build: .
    volumes:
      - .:/app
    environment:
      - PYTHONPATH=/app

  # Test databases - only used for development/testing
  db1:
    image: postgres:13
    profiles:
      - test
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: employees_db
    ports:
      - "5432:5432"
    volumes:
      - ./test_databases/db1/init.sql:/docker-entrypoint-initdb.d/init.sql

  db2:
    image: postgres:13
    profiles:
      - test
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: orders_db
    ports:
      - "5433:5432"
    volumes:
      - ./test_databases/db2/init.sql:/docker-entrypoint-initdb.d/init.sql
