version: '3'
services:
  db1:
    image: postgres:13
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: employees_db
    volumes:
      - ./init-db1:/docker-entrypoint-initdb.d
    ports:
      - "5432:5432"

  db2:
    image: postgres:13
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: orders_db
    volumes:
      - ./init-db2:/docker-entrypoint-initdb.d
    ports:
      - "5433:5432"

  datadictionary:
    build: .
    volumes:
      - .:/app
    depends_on:
      - db1
      - db2
